plugins {
    id 'com.android.application'
}

android {
    namespace 'ir.pedalpro.app'
    compileSdk 36
    buildFeatures { buildConfig true }

    defaultConfig {
        applicationId 'ir.pedalpro.app'
        minSdk 26
        targetSdk 36
        versionCode 9
        versionName '1.4.4'
    }

    flavorDimensions 'distribution'
    productFlavors {
        bazaar {
            dimension 'distribution'
            buildConfigField 'String', 'STORE_CHANNEL', '"bazaar"'
        }
        myket {
            dimension 'distribution'
            buildConfigField 'String', 'STORE_CHANNEL', '"myket"'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core:1.15.0'
    implementation 'com.google.firebase:firebase-messaging:24.1.2'
}
